# ---- Build Stage ----
FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

# ---- Nginx Stage ----
FROM nginx:alpine
# React Build kopieren
COPY --from=build /app/dist /usr/share/nginx/html
# Nginx-Config kopieren
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]