# Generated by Django 6.0.1 on 2026-02-01 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('folder_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='public/season/covers/')),
                ('folder_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='public/series/covers/')),
                ('year_released', models.IntegerField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('folder_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='media_manager.genre')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('media', models.ManyToManyField(blank=True, to='media_manager.media')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='media_manager.media')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_filler', models.BooleanField(blank=True, default=False, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='media_manager.season')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='media_manager.media')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='media_manager.series'),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('frame_count', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('codec_video', models.CharField(blank=True, max_length=50, null=True)),
                ('codec_audio', models.CharField(blank=True, max_length=50, null=True)),
                ('container', models.CharField(blank=True, max_length=20, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='media_manager.episode')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='media_manager.language')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='media_manager.movie')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('episode__isnull', True), ('movie__isnull', False)), models.Q(('episode__isnull', False), ('movie__isnull', True)), _connector='OR'), name='mediafile_movie_xor_episode')],
            },
        ),
    ]
