# Generated by Django 6.0.1 on 2026-02-01 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='public/series/covers/')),
                ('year_released', models.IntegerField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('folder_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('needs_changing', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
    ]
