# Generated by Django 6.0.1 on 2026-02-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0003_oldgenre_alter_oldseries_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldgenre',
            options={'managed': False},
        ),
    ]
