# Generated by Django 6.0.1 on 2026-02-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0004_alter_oldgenre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='oldgenre',
            table='mediamanager_genre',
        ),
    ]
