# Generated by Django 6.0.1 on 2026-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0005_alter_collection_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldSeriesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mediamanager_series_genres',
                'managed': False,
            },
        ),
    ]
