# Generated by Django 6.0.1 on 2026-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0006_oldseriesgenres'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('frame_count', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'mediamanager_language_episode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_filler', models.BooleanField(blank=True, default=False, null=True)),
                ('visited', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'mediamanager_episode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('folder_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'mediamanager_language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='public/season/covers/')),
                ('folder_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('needs_changing', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'mediamanager_season',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='collection',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='collection', to='media_manager.media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/media/covers/'),
        ),
    ]
