# Generated by Django 6.0.1 on 2026-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0007_languageepisode_oldepisode_oldlanguage_oldseason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldLanguageEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('frame_count', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'mediamanager_language_episode',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LanguageEpisode',
        ),
    ]
