# Generated by Django 6.0.1 on 2026-02-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0008_oldlanguageepisode_delete_languageepisode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oldlanguageepisode',
            table='mediamanager_languageepisode',
        ),
    ]
