# Generated by Django 6.0.1 on 2026-02-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0009_alter_oldlanguageepisode_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldEpisode',
        ),
        migrations.DeleteModel(
            name='OldGenre',
        ),
        migrations.DeleteModel(
            name='OldLanguage',
        ),
        migrations.DeleteModel(
            name='OldLanguageEpisode',
        ),
        migrations.DeleteModel(
            name='OldSeason',
        ),
        migrations.DeleteModel(
            name='OldSeries',
        ),
        migrations.DeleteModel(
            name='OldSeriesGenres',
        ),
    ]
