# Generated by Django 6.0.1 on 2026-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0010_delete_oldepisode_delete_oldgenre_delete_oldlanguage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='sub_folder_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
