# Generated by Django 6.0.1 on 2026-02-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0011_media_sub_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date_last_synced',
            field=models.DateField(blank=True, null=True),
        ),
    ]
