# Generated by Django 6.0.1 on 2026-02-09 13:19

import backendapp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0012_media_date_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tracked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=backendapp.storage.PiStorage(), upload_to='public/anime/covers/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=backendapp.storage.PiStorage(), upload_to='public/season/covers/'),
        ),
    ]
