# Generated by Django 6.0.1 on 2026-03-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0013_media_tracked_alter_media_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='media',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='media_manager.mediastatus'),
        ),
    ]
